### ISSUE TITLE
Rebasing items

### ISSUE THREAD

**Issue by blastur** [jacebrowning/doorstop#233]
I'm quite new to Doorstop, but as my document(s) have kept growing, I have sometimes found myself wanting to rebase items. 

For example, I have not yet published any of my documents to the rest of the organisation and I've already deleted several items. This leaves "gaps" in the UIDs, which is kind of ugly. I realize once the document has been published, it's perfectly sane to never re-use a deleted UID for new items, but in my case where I'm just doing local work, it would be nice if deleted UIDs could be redistributed in my document. If compared to Git, this would be rebasing before the code has been pushed elsewhere, it's just a convenient local tool, just like doorstop "reorder" is very useful.

The other use for rebasing is when several collaborators are working on the same document. Two developers create the same UIDs and when it's time to merge, it becomes a mess. It would be nice if developer B could pull developer A's tree and rebase ontop of that. Doorstop would then "doorstop add" any colliding items in developer B's tree ontop of developer A's tree

**Comment by michaelnt** [comment]
I renumber things by exporting to excel and using fill down on the uid
column.

If two people are adding requirements you can use the server to ensure you
don't use the same I'd.

**Comment by jacebrowning** [comment]
I would love it if someone with more time on their hands could start expanding the documentation to include a "use cases" section.

`doorstop reorder` and `doorstop-server` are basically undocumented outside of the command-line help text.

**Comment by blastur** [comment]
I recently did a presentation on doorstop at my company, it's based on my findings by digging through the code, the whitepaper and my own experiments. I think I could summarize it in a document if you want.

**Comment by jacebrowning** [comment]
That would be great! 

The documentation is all under `docs/` and can be viewed locally with `mkdocs serve`.

**Comment by blastur** [comment]
michaelnt, I tried rebasing by exporting to Excel and renumbering the UIDs from there. What is your approach to re-importing it? When I imported it into my existing document, there were leftovers from the original UID numbering. I could import it to a new document, but then I'd have to delete the old document and rename the new one (through cmdline) into place. Am I doing it wrong?

It's a little bit of hassle IMO, doorstop could really do with a proper UID rebase command.

**Comment by michaelnt** [comment]
Yes it won't delete the uids that are no longer needed. I just delete those
manually using svn commands.

Would a renumber command work?

**Comment by blastur** [comment]
I imagine a renumber command that will redistribute items from number 1 according to the order they appear (based on level).

Example:
```
outline:
    - SRD015: # ..
        - SRD044: # ..
    - SRD022: # ..
        - SRD031: # ..
        - SRD034: # ..
```

`doorstop renumber SRD` should produce

```
outline:
    - SRD001: # ..
        - SRD002: # ..
    - SRD003: # ..
        - SRD004: # ..
        - SRD005: # ..
```

It could of course be called something other than renumber. I find the "git rebase" command similar, so I would just call it `doorstop rebase SRD`. You can allow to specify a starting UID, otherwise it'll start from SRD001. For example `doorstop rebase SRD --ref 015` would produce

```
outline:
    - SRD015: # ..
        - SRD016: # ..
    - SRD017: # ..
        - SRD018: # ..
        - SRD019: # ..
```
