### ISSUE TITLE
Headings are lost during reorder

### ISSUE THREAD

**Issue by blastur** [jacebrowning/doorstop#246]
For a document ABC that has the following item order:
```
initial: 1.0
outline:
    - ABC001: # Overview
        - ABC002: # Terms and definition
    - ABC003: # This is a requirement
```

And ABC001 and ABC002 are headings (non-normative and level 1.0 and 1.1.0). If I run the reorder command on this and change nothing, ABC002 is no longer a heading. So it seems that doorstop assumes that 1.1.0 is the same as 1.1, which it is in terms of ordering, but it ruins the heading property of the item.

Steps to reproduce:
1. Create the ABC document as shown above
2. Publish the document, notice 1.1 is a heading.
3. Run ```doorstop reorder ABC```
4. Re-publish, notice 1.1 is no longer a heading.

**Comment by michaelnt** [comment]
This is a limitation that has always existed in the reorder command, I recreated this in doorstop 1.2.1 at least. I get a slightly different index.yml to yours.

```
initial: 1.0
outline:
    - ABC001: # Heading 1
        - ABC002: # Sub Heading
        - ABC003: #  More requirements
```

You can work around the problem by adding an item under the heading either separately or during reorder, i.e.

```
initial: 1.0
outline:
    - ABC001: # Heading 1
        - ABC002: # Sub Heading
                 - NEW : # A new item at level 1.1.1
        - ABC003: #  More requirements
```

Why have a heading without any items under it?

Perhaps doorstop could issue a warning whilst creating the index.yml?
