### ISSUE TITLE
Custom item template

### ISSUE THREAD

**Issue by RomainTT** [jacebrowning/doorstop#330]
Possibly embraces #70 and #319, with a little bit more.

It would be nice being able to write item templates like this:

```yaml
custom_field: custom_default_value
text: |
    Default text that appears in each new item.
```

And tell a document to use this template in `.doorstop.yml`:

```yaml
settings:
  digits: 3
  prefix: SRS
  sep: ''
  template: my_template.yml
```

Then, when I create a new item in SRS it has immediatly the content of the template:

```yaml
active: true
derived: false
level: 1.0
links: []
normative: true
ref: ''
reviewed: None
custom_field: custom_default_value
text: |
    Default text that appears in each new item.
```

Personally, I would need this to include some mandatory fields in items that are describing tests. And I want all my items to have the same fields with the same default value.

Meanwhile, I don’t know where should be located the template files, maybe anywhere since doorstop can search the whole depository?
