### ISSUE TITLE
Add a dictionary of default item values to documents.

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/doorstop#70]
Example `.doorstop.yml` file:

```
settings:
...
defaults:
  custom-attr1: True
  custom-attr2: "Hello, world!"
```

Example usage:

```
item = document.add_item()
assert item.get('custom-attr2') == "Hello, world!"
```
##
